/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppChangePasswordRouteImport } from './routes/_app.change-password'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppRecordsIndexRouteImport } from './routes/_app.records.index'
import { Route as AppRecordsIdRouteImport } from './routes/_app.records.$id'
import { Route as AppRecordsNewRouteImport } from './routes/_app.records.new'
import { Route as AppRecordsIdCertificateRouteImport } from './routes/_app.records.$id.certificate'
import { Route as AppRecordsIdEditRouteImport } from './routes/_app.records.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsIndexRoute = AppRecordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRecordsRoute,
} as any)
const AppRecordsIdRoute = AppRecordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecordsRoute,
} as any)
const AppRecordsNewRoute = AppRecordsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRecordsRoute,
} as any)
const AppRecordsIdCertificateRoute = AppRecordsIdCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => AppRecordsIdRoute,
} as any)
const AppRecordsIdEditRoute = AppRecordsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppRecordsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AppChangePasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/records': typeof AppRecordsRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/records/$id': typeof AppRecordsIdRouteWithChildren
  '/records/new': typeof AppRecordsNewRoute
  '/records/': typeof AppRecordsIndexRoute
  '/records/$id/certificate': typeof AppRecordsIdCertificateRoute
  '/records/$id/edit': typeof AppRecordsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AppChangePasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/records/$id': typeof AppRecordsIdRouteWithChildren
  '/records/new': typeof AppRecordsNewRoute
  '/records': typeof AppRecordsIndexRoute
  '/records/$id/certificate': typeof AppRecordsIdCertificateRoute
  '/records/$id/edit': typeof AppRecordsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/change-password': typeof AppChangePasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/records': typeof AppRecordsRouteWithChildren
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/records/$id': typeof AppRecordsIdRouteWithChildren
  '/_app/records/new': typeof AppRecordsNewRoute
  '/_app/records/': typeof AppRecordsIndexRoute
  '/_app/records/$id/certificate': typeof AppRecordsIdCertificateRoute
  '/_app/records/$id/edit': typeof AppRecordsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/change-password'
    | '/dashboard'
    | '/records'
    | '/admin/users'
    | '/records/$id'
    | '/records/new'
    | '/records/'
    | '/records/$id/certificate'
    | '/records/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/change-password'
    | '/dashboard'
    | '/admin/users'
    | '/records/$id'
    | '/records/new'
    | '/records'
    | '/records/$id/certificate'
    | '/records/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/change-password'
    | '/_app/dashboard'
    | '/_app/records'
    | '/_app/admin/users'
    | '/_app/records/$id'
    | '/_app/records/new'
    | '/_app/records/'
    | '/_app/records/$id/certificate'
    | '/_app/records/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/change-password': {
      id: '/_app/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/': {
      id: '/_app/records/'
      path: '/'
      fullPath: '/records/'
      preLoaderRoute: typeof AppRecordsIndexRouteImport
      parentRoute: typeof AppRecordsRoute
    }
    '/_app/records/$id': {
      id: '/_app/records/$id'
      path: '/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AppRecordsIdRouteImport
      parentRoute: typeof AppRecordsRoute
    }
    '/_app/records/new': {
      id: '/_app/records/new'
      path: '/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof AppRecordsNewRouteImport
      parentRoute: typeof AppRecordsRoute
    }
    '/_app/records/$id/certificate': {
      id: '/_app/records/$id/certificate'
      path: '/certificate'
      fullPath: '/records/$id/certificate'
      preLoaderRoute: typeof AppRecordsIdCertificateRouteImport
      parentRoute: typeof AppRecordsIdRoute
    }
    '/_app/records/$id/edit': {
      id: '/_app/records/$id/edit'
      path: '/edit'
      fullPath: '/records/$id/edit'
      preLoaderRoute: typeof AppRecordsIdEditRouteImport
      parentRoute: typeof AppRecordsIdRoute
    }
  }
}

interface AppRecordsIdRouteChildren {
  AppRecordsIdCertificateRoute: typeof AppRecordsIdCertificateRoute
  AppRecordsIdEditRoute: typeof AppRecordsIdEditRoute
}

const AppRecordsIdRouteChildren: AppRecordsIdRouteChildren = {
  AppRecordsIdCertificateRoute: AppRecordsIdCertificateRoute,
  AppRecordsIdEditRoute: AppRecordsIdEditRoute,
}

const AppRecordsIdRouteWithChildren = AppRecordsIdRoute._addFileChildren(
  AppRecordsIdRouteChildren,
)

interface AppRecordsRouteChildren {
  AppRecordsIdRoute: typeof AppRecordsIdRouteWithChildren
  AppRecordsNewRoute: typeof AppRecordsNewRoute
  AppRecordsIndexRoute: typeof AppRecordsIndexRoute
}

const AppRecordsRouteChildren: AppRecordsRouteChildren = {
  AppRecordsIdRoute: AppRecordsIdRouteWithChildren,
  AppRecordsNewRoute: AppRecordsNewRoute,
  AppRecordsIndexRoute: AppRecordsIndexRoute,
}

const AppRecordsRouteWithChildren = AppRecordsRoute._addFileChildren(
  AppRecordsRouteChildren,
)

interface AppRouteChildren {
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppRecordsRoute: typeof AppRecordsRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppRecordsRoute: AppRecordsRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
